spring:
  redis:
    host: 192.168.18.132
    port: 6379
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: majun110
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    instance:
      hostname: order
env: dev
girl:
  name: jiangjiao
  age: 19
